# 내가 43250원이 있다
# 만원 짜리는 몇개 있고
# 오천원 짜리는 몇개 있고
# 500원 몇개있고
# 100원 몇개있고
# 50원 몇개있고
# 10원 몇개있다

# money=43250 
# if money // 10000 >=1:
#     print(f"만원 짜리는{money//10000}개 있고")
#     money = money - (money//10000)*10000
# if money // 5000 >=1:
#     print(f"5000원 짜리는 {money//5000}개 있고")
# elif money // 5000 <=1:
#     print(f"5000원 짜리는 없다")
#     money = money - (money//5000)*5000
# if money // 500 >=1:
#     print(f"500원 짜리는 {money//500}개 있고")
#     money = money - (money//500)*500
# if money // 100 >=1:
#     print(f"100원 짜리는 {money//100}개 있고")
#     money = money - (money//100)*100
# if money // 50 >=1:
#     print(f"50원 짜리는 {money//50}개 있고")
#     money = money - (money//50)*50
# if money // 10 >=1:
#     print(f"10원 짜리는 {money//10}개 있고")
# # and 둘다 맞아야하고
# or 둘중 하나 또는 다 만족

# a=12
# a=40
# answer = f"{a}는"
# if a%2==0 and a%3==0:
#     answer += "2와 3의 공배수 입니다"
# elif a%2==0:
#     answer += "2의 배수 입니다"
# elif a%3==0:
#     answer += "3의 배수 입니다"
# else:
#     answer += "2와 3의 공배수가 아닙니다"
# print(answer)

